export {default as Home} from "./Home/Home"
export {default as SignIn} from "./SignIn/SignIn"
export {default as Verify} from "./SignIn/Verify"
export {default as EmailConfirmed} from "./SignIn/EmailConfirmed"
export {default as Blog} from "./Blog/Blog"
export {default as Testimonial} from "./Testimonial/Testimonial"
export {default as Contact} from "./Contact/Contact"
export {default as Integrations} from "./Integrations/Integrations"
export {default as Footer} from "./Footer/Footer"
export {default as ChatMessage} from "./ChatMessage/ChatMessage"
export {default as Sidebar} from "./SignIn/Sidebar"
// export {default as Illustration} from "./Black Background/Illustration"